# vim: sw=2
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: con

on:
- push

jobs:
  con:
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-2019
        - windows-2022
        - macos-11
        - macos-12
        - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: cat Con | grep test
    - run: cat '한국어 NFC 테스트' | grep NFC
    - run: cat '한국어 NFC 테스트' | grep NFD
