# vim: sw=2
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: con

on:
- push

jobs:
  con:
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-2019
        - macos-11
        - macos-10.15
        - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
